export const expandedPages = {
  en: {
    about: {
      eyebrow: 'About Us',
      title: ['Saksouk —', 'Experience Since 1950'],
      intro: 'Decades of business experience, local market knowledge and distribution expertise—focused on helping our partners build a strong and sustainable presence in Syria.',
      storyTitle: 'Experience across industries. A focused future in healthcare.',
      story: [
        'We are part of Saksouk International Group, a diversified business group with a business and trading history dating back to 1950. The group operates across a range of sectors, including animal feed manufacturing and trading, aluminum manufacturing and trading, contracting and construction, agriculture, and the trading and import of vehicles and spare parts.',
        'At the forefront of the group’s activities is Saksouk Pharmaceutical Warehouse, established in 2000, bringing more than two decades of experience in the trade and distribution of pharmaceutical products, supported by extensive knowledge of market requirements, distribution operations, and relationships with companies, suppliers, and customers.',
        'Throughout its decades of operation, the group has continuously focused on developing its businesses, attracting qualified professionals and experienced talent, and building specialized teams capable of responding to evolving market needs and supporting our partners.',
        'Today, we continue this journey by expanding our activities and building strategic partnerships with companies and brands seeking to enter the Syrian market or expand their presence within it.',
        'We offer our partners decades of experience, local market knowledge, distribution expertise, and the infrastructure needed to build a strong and sustainable presence in the Syrian market.',
      ],
      vision: { label: 'Our vision', title: 'To be the most dependable pharmaceutical distribution partner in Syria.', text: 'We envision a connected healthcare supply chain where quality products reach the organizations and communities that need them with consistency and care.' },
      goal: { label: 'Our goal', title: 'Make access simpler, clearer and more reliable.', text: 'We work to build resilient routes to market, responsive partner support and disciplined operations across every stage of distribution.' },
      teamTitle: 'People behind dependable supply.',
      teamText: 'Our team brings together commercial, operational, regulatory and relationship-building expertise. Shared standards and practical collaboration keep the whole organization moving in one direction.',
      stats: [
        { value: '2,982', label: 'Pharmacies in our reach' },
        { value: '03', label: 'Core product families' },
        { value: '04', label: 'Operating principles' },
        { value: '01', label: 'Connected partner network' },
      ],
    },
    news: {
      eyebrow: 'News & Insights',
      title: ['Health systems,', 'medicines and supply.'],
      intro: 'A focused reading room covering pharmaceutical access, medicine safety and responsible product distribution. Articles summarize public information from authoritative health organizations.',
      posts: [
        { category: 'Syria health update', date: '30 December 2025', title: 'Essential medicines remain central to health access in Syria', excerpt: 'WHO reported that support during 2025 included nearly 10 million treatment courses delivered to health facilities, alongside continued work on essential services and disease surveillance.', image: '/images/blog-cold-chain.png', source: 'World Health Organization', href: 'https://www.emro.who.int/syria/news/what-care-looked-like-in-syria-2025-key-moments-in-photos.html' },
        { category: 'Supply chain', date: '6 February 2026', title: 'Better forecasting is shaping more resilient medicine supply chains', excerpt: 'WHO’s 2026 review of medicine procurement highlights national ownership, better forecasting, connected digital systems and active supply-risk management as emerging priorities.', image: '/images/blog-medicine-safety.png', source: 'World Health Organization', href: 'https://www.who.int/westernpacific/publications/i/item/who-wer1014-6-13-22' },
        { category: 'Product quality', date: 'Updated 2026', title: 'Responsible supplement distribution starts with quality and traceability', excerpt: 'FDA resources continue to emphasize accurate labeling, safety responsibilities and clear processes for new dietary ingredients—useful principles for every responsible distributor.', image: '/images/blog-supplement-quality.png', source: 'U.S. Food & Drug Administration', href: 'https://www.fda.gov/food/dietary-supplements/whats-new-dietary-supplements' },
      ],
    },
    work: {
      eyebrow: 'Work with us',
      title: ['Build meaningful work', 'around better access.'],
      intro: 'Saksouk welcomes people who value responsibility, clarity and teamwork across the pharmaceutical supply chain.',
      paths: [
        { title: 'Commercial & partnerships', text: 'Help manufacturers, suppliers and healthcare organizations build practical routes to market.' },
        { title: 'Operations & distribution', text: 'Support accurate inventory, responsible handling and dependable dispatch coordination.' },
        { title: 'Quality & regulatory', text: 'Bring structured thinking to documentation, product requirements and responsible processes.' },
      ],
      process: ['Introduce yourself', 'Tell us where you add value', 'Meet the relevant team', 'Explore the right opportunity'],
    },
    partner: {
      eyebrow: 'Partner with Saksouk',
      title: ['Bring healthcare products', 'closer to the market.'],
      intro: 'We collaborate with local, regional and international organizations seeking a capable pharmaceutical partner in Syria.',
      benefits: [
        { title: 'Local market understanding', text: 'Practical knowledge of healthcare channels, customer needs and commercial coordination.' },
        { title: 'Connected distribution', text: 'Relationships spanning pharmacies, healthcare institutions and industry stakeholders.' },
        { title: 'Launch support', text: 'Business development and local coordination designed around each product opportunity.' },
        { title: 'Long-term relationships', text: 'Clear communication, shared priorities and a partnership mindset beyond a single transaction.' },
      ],
    },
    products: {
      medicine: { eyebrow: 'Human medicines', title: ['Medicines that support', 'everyday healthcare.'], intro: 'Saksouk distributes and promotes high-quality human medicines through professional healthcare channels.', image: '/images/blog-medicine-safety.png', points: ['Finished pharmaceutical products', 'In-licensed medicine opportunities', 'Support for healthcare and pharmacy channels', 'Commercial and distribution coordination'] },
      cosmetics: { eyebrow: 'Cosmetics', title: ['Care products selected', 'with purpose.'], intro: 'Our cosmetics activity connects relevant personal-care products with professional market knowledge and responsible distribution.', image: '/images/pharma-quality-v3.jpg', points: ['Dermocosmetic and personal-care categories', 'Market-entry and product-development support', 'Professional pharmacy-channel distribution', 'Partner-focused commercial coordination'] },
      supplements: { eyebrow: 'Nutritional supplements', title: ['Quality-led support', 'for everyday wellbeing.'], intro: 'We support the responsible distribution of nutritional supplements through clear product positioning and trusted healthcare channels.', image: '/images/blog-supplement-quality.png', points: ['Vitamins, minerals and selected supplements', 'Clear product and partner communication', 'Pharmacy and healthcare-channel reach', 'Quality-conscious distribution support'] },
    },
  },
  ar: {
    about: {
      eyebrow: 'من نحن',
      title: ['سكسوك —', 'خبرة تمتد منذ عام 1950'],
      intro: 'خبرة تمتد لعقود، ومعرفة بالسوق، وخبرة في التوزيع، وبنية تحتية تساعد شركاءنا على بناء حضور قوي ومستدام في السوق السورية.',
      storyTitle: 'خبرة متنوعة ومستقبل يركز على الرعاية الصحية.',
      story: [
        'نحن جزء من مجموعة شركات سكسوك العالمية، التي تمتد خبرتها في مجال الأعمال والتجارة منذ عام 1950، وتعمل في مجموعة متنوعة من القطاعات، تشمل صناعة وتجارة الأعلاف، صناعة وتجارة الألمنيوم، المقاولات والبناء، الزراعة، وتجارة واستيراد السيارات وقطع الغيار.',
        'ويأتي مستودع سكسوك للأدوية في مقدمة أنشطة المجموعة، حيث بدأ نشاطه منذ عام 2000، ليقدم خبرة تمتد لأكثر من عقدين في تجارة وتوزيع المنتجات الدوائية، مع معرفة واسعة بمتطلبات السوق وآليات التوزيع والتعامل مع الشركات والموردين والعملاء.',
        'وعلى مدى عقود، حرصت المجموعة على تطوير أعمالها باستمرار واستقطاب الخبرات والكفاءات المهنية، وبناء فرق عمل متخصصة قادرة على مواكبة تطورات الأسواق واحتياجات شركائنا.',
        'واليوم، نواصل مسيرة التطور من خلال توسيع نشاطنا وبناء شراكات استراتيجية مع الشركات والعلامات التجارية الراغبة في دخول السوق السورية أو توسيع حضورها فيها.',
        'نقدم لشركائنا خبرة تمتد لعقود، ومعرفة بالسوق، وخبرة في التوزيع، وبنية تحتية تساعدهم على بناء حضور قوي ومستدام في السوق السورية.',
      ],
      vision: { label: 'رؤيتنا', title: 'أن نكون شريك التوزيع الدوائي الأكثر موثوقية في سوريا.', text: 'نتطلع إلى سلسلة إمداد صحية مترابطة تصل فيها المنتجات عالية الجودة إلى المؤسسات والمجتمعات التي تحتاجها باستمرارية وعناية.' },
      goal: { label: 'هدفنا', title: 'جعل الوصول أبسط وأوضح وأكثر موثوقية.', text: 'نعمل على بناء مسارات مرنة إلى السوق ودعم سريع للشركاء وعمليات منضبطة في كل مرحلة من مراحل التوزيع.' },
      teamTitle: 'فريق يقف خلف إمداد موثوق.',
      teamText: 'يجمع فريقنا الخبرات التجارية والتشغيلية والتنظيمية وخبرات بناء العلاقات. وتضمن المعايير المشتركة والتعاون العملي تحرك المؤسسة بأكملها في اتجاه واحد.',
      stats: [
        { value: '2,982', label: 'صيدلية ضمن نطاقنا' },
        { value: '03', label: 'عائلات منتجات أساسية' },
        { value: '04', label: 'مبادئ تشغيلية' },
        { value: '01', label: 'شبكة شركاء مترابطة' },
      ],
    },
    news: {
      eyebrow: 'الأخبار والرؤى',
      title: ['الأنظمة الصحية،', 'الأدوية وسلاسل الإمداد.'],
      intro: 'مساحة مركزة لمتابعة الوصول إلى الأدوية وسلامتها والتوزيع المسؤول، استناداً إلى معلومات عامة صادرة عن مؤسسات صحية موثوقة.',
      posts: [
        { category: 'تحديث صحي من سوريا', date: '30 كانون الأول 2025', title: 'الأدوية الأساسية تبقى محوراً رئيسياً للوصول إلى الرعاية في سوريا', excerpt: 'أفادت منظمة الصحة العالمية بأن دعم عام 2025 شمل إيصال ما يقارب 10 ملايين دورة علاجية إلى المرافق الصحية، إلى جانب استمرار دعم الخدمات الأساسية والترصد الصحي.', image: '/images/blog-cold-chain.png', source: 'منظمة الصحة العالمية', href: 'https://www.emro.who.int/syria/news/what-care-looked-like-in-syria-2025-key-moments-in-photos.html' },
        { category: 'سلسلة الإمداد', date: '6 شباط 2026', title: 'التنبؤ الأفضل يدعم سلاسل إمداد دوائي أكثر مرونة', excerpt: 'تسلط مراجعة منظمة الصحة العالمية الضوء على الملكية الوطنية وتحسين التنبؤ وربط الأنظمة الرقمية وإدارة مخاطر الإمداد كأولويات متنامية.', image: '/images/blog-medicine-safety.png', source: 'منظمة الصحة العالمية', href: 'https://www.who.int/westernpacific/publications/i/item/who-wer1014-6-13-22' },
        { category: 'جودة المنتجات', date: 'محدّث في 2026', title: 'التوزيع المسؤول للمكملات يبدأ من الجودة وإمكانية التتبع', excerpt: 'تواصل موارد إدارة الغذاء والدواء التأكيد على دقة الملصقات ومسؤوليات السلامة والعمليات الواضحة للمكونات الغذائية الجديدة.', image: '/images/blog-supplement-quality.png', source: 'إدارة الغذاء والدواء الأمريكية', href: 'https://www.fda.gov/food/dietary-supplements/whats-new-dietary-supplements' },
      ],
    },
    work: {
      eyebrow: 'اعمل معنا',
      title: ['اصنع عملاً مؤثراً', 'لتحسين الوصول الصحي.'],
      intro: 'ترحب سكسوك بالأشخاص الذين يقدرون المسؤولية والوضوح والعمل الجماعي ضمن سلسلة الإمداد الدوائي.',
      paths: [
        { title: 'التجارة والشراكات', text: 'ساعد المصنعين والموردين ومؤسسات الرعاية الصحية على بناء مسارات عملية إلى السوق.' },
        { title: 'العمليات والتوزيع', text: 'ادعم دقة المخزون والمناولة المسؤولة والتنسيق الموثوق للإرسال.' },
        { title: 'الجودة والشؤون التنظيمية', text: 'قدّم تفكيراً منظماً للوثائق ومتطلبات المنتجات والعمليات المسؤولة.' },
      ],
      process: ['عرّفنا بنفسك', 'أخبرنا أين تضيف قيمة', 'التقِ بالفريق المختص', 'استكشف الفرصة المناسبة'],
    },
    partner: {
      eyebrow: 'كن شريكاً لسكسوك',
      title: ['قرّب منتجات الرعاية الصحية', 'من السوق.'],
      intro: 'نتعاون مع المؤسسات المحلية والإقليمية والدولية التي تبحث عن شريك دوائي قادر في سوريا.',
      benefits: [
        { title: 'فهم السوق المحلي', text: 'معرفة عملية بقنوات الرعاية الصحية واحتياجات العملاء والتنسيق التجاري.' },
        { title: 'توزيع مترابط', text: 'علاقات تمتد عبر الصيدليات ومؤسسات الرعاية الصحية وأصحاب المصلحة في القطاع.' },
        { title: 'دعم الإطلاق', text: 'تطوير أعمال وتنسيق محلي مصمم حول كل فرصة منتج.' },
        { title: 'علاقات طويلة الأمد', text: 'تواصل واضح وأولويات مشتركة وعقلية شراكة تتجاوز المعاملة الواحدة.' },
      ],
    },
    products: {
      medicine: { eyebrow: 'الأدوية البشرية', title: ['أدوية تدعم', 'الرعاية الصحية اليومية.'], intro: 'تقوم سكسوك بتوزيع وترويج مجموعة من الأدوية البشرية عالية الجودة عبر قنوات الرعاية الصحية المهنية.', image: '/images/blog-medicine-safety.png', points: ['المنتجات الدوائية النهائية', 'فرص الأدوية المرخصة', 'دعم قنوات الرعاية الصحية والصيدليات', 'التنسيق التجاري والتوزيعي'] },
      cosmetics: { eyebrow: 'مستحضرات التجميل', title: ['منتجات عناية مختارة', 'بعناية وهدف واضح.'], intro: 'يربط نشاطنا في مستحضرات التجميل منتجات العناية المناسبة بمعرفة السوق والتوزيع المسؤول.', image: '/images/pharma-quality-v3.jpg', points: ['فئات العناية الجلدية والشخصية', 'دعم دخول السوق وتطوير المنتجات', 'التوزيع عبر قنوات الصيدليات', 'تنسيق تجاري يركز على الشريك'] },
      supplements: { eyebrow: 'المكملات الغذائية', title: ['دعم قائم على الجودة', 'للعافية اليومية.'], intro: 'ندعم التوزيع المسؤول للمكملات الغذائية من خلال تموضع واضح للمنتجات وقنوات رعاية صحية موثوقة.', image: '/images/blog-supplement-quality.png', points: ['الفيتامينات والمعادن والمكملات المختارة', 'تواصل واضح حول المنتج والشراكة', 'الوصول إلى قنوات الصيدليات والرعاية الصحية', 'دعم توزيع واعٍ للجودة'] },
    },
  },
} as const;
